"""Build the single-file MT5 distribution from the tested shared sources."""

from pathlib import Path
import argparse
import re

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "mt5/Standalone/GoldTrendSweep.mq5"
MAIN = ROOT / "mt5/Experts/GoldTrendSweep.mq5"


def render_main():
    source = MAIN.read_text()
    header = "\n".join((ROOT / "mt5/Include" / name).read_text().rstrip()
                       for name in ("GoldRiskMath.mqh", "GoldSignalMath.mqh"))
    marker = "#include <GoldRiskMath.mqh>"
    block = "// BEGIN GENERATED RISK MODULE: edit Include/GoldRiskMath.mqh or GoldSignalMath.mqh, then run scripts/build_standalone.py\n" + header.rstrip() + "\n// END GENERATED RISK MODULE"
    if source.count(marker) == 1:
        return source.replace(marker, block)
    pattern = r"// BEGIN GENERATED RISK MODULE[^\n]*\n.*?// END GENERATED RISK MODULE"
    if len(re.findall(pattern, source, re.S)) != 1:
        raise ValueError("Expected exactly one generated risk module")
    return re.sub(pattern, lambda _: block, source, flags=re.S)


def render():
    return "// Generated by scripts/build_standalone.py; edit Experts/GoldTrendSweep.mq5 instead.\n" + render_main()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    main_content = render_main()
    if args.check:
        if MAIN.read_text() != main_content or not OUTPUT.exists() or OUTPUT.read_text() != content:
            raise SystemExit("Single-file distributions are missing or out of date")
        print("Both single-file distributions match shared sources.")
    else:
        MAIN.write_text(main_content)
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(content)
        print(f"Built {OUTPUT.relative_to(ROOT)}")
