"""Build the single-file MT5 distribution from the tested shared sources."""

from pathlib import Path
import argparse

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "mt5/Standalone/GoldTrendSweep.mq5"


def render():
    source = (ROOT / "mt5/Experts/GoldTrendSweep.mq5").read_text()
    header = (ROOT / "mt5/Include/GoldRiskMath.mqh").read_text()
    marker = "#include <GoldRiskMath.mqh>"
    if source.count(marker) != 1:
        raise ValueError("Expected exactly one shared risk include")
    return "// Generated by scripts/build_standalone.py; edit the shared sources instead.\n" + source.replace(marker, header.rstrip())


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != content:
            raise SystemExit("Standalone distribution is missing or out of date")
        print("Standalone distribution matches shared sources.")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(content)
        print(f"Built {OUTPUT.relative_to(ROOT)}")
